import { AuditTemplateItem, OrResponsibleRole, OrAuditSector, Role } from "./types";

export const LOCATIONS = ["Salta", "Jujuy"] as const;

export const AUDITORS = [
  { id: "1", name: "Melisa Condori" },
  { id: "2", name: "Nelson Notario" },
];

export const OR_ROLE_LABELS: Record<OrResponsibleRole, string> = {
  asesor: "Asesor",
  tecnico: "Técnico",
  controller: "Controller",
  lavador: "Lavador",
  repuestos: "Repuestos",
};

export const OR_SECTOR_LABELS: Record<OrAuditSector, string> = {
  recepcion: "Asesor / Recepción",
  taller: "Taller / Técnico",
  control_calidad: "Control de calidad / Controller",
  lavado: "Lavado",
  repuestos: "Repuestos / Ampliaciones",
  resumen: "Resumen final",
};

export const OR_PARTICIPANTS = {
  asesorServicio: ["Mauro Gutierrez", "Cristian Cardozo", "Carlos Farina"],
  tecnico: ["J. Araya", "N. Poclava", "R. Garcia", "P. Fernandez", "E. Cruz", "I. Alanoca"],
  controller: ["Marcelo Pereyra", "Nelson Notario"],
  lavador: ["Claudio Bravo", "Santiago Silva", "Alejandro Mamani"],
  repuestos: ["Repuestos 1", "Repuestos 2"],
} as const;

export const OR_CHECKLIST_ITEMS: AuditTemplateItem[] = [
  {
    id: "or-01",
    text: "01. Ingreso y entrega de unidad",
    description: "Verificar hora de ingreso, fecha y hora prometida de entrega y fecha de cierre.",
    guidance: "Confirmar que la OR tenga ingreso, compromiso y cierre completos.",
    required: true,
    block: "Recepción",
    sector: "recepcion",
    responsibleRoles: ["asesor"],
    allowsNa: false,
    weight: 1,
    order: 1,
    priority: "high",
    active: true,
  },
  {
    id: "or-02",
    text: "02. Inspección inicial",
    description: "Control de auxilio, extintor, gato, herramientas y objetos de valor.",
    guidance: "Debe quedar reflejado en recepción y en la OR.",
    required: true,
    block: "Recepción",
    sector: "recepcion",
    responsibleRoles: ["asesor"],
    allowsNa: false,
    weight: 1,
    order: 2,
    priority: "high",
    active: true,
  },
  {
    id: "or-03",
    text: "03. Presupuesto ofrecido y forma de pago",
    description: "Debe existir oferta de presupuesto según circular vigente y forma de pago definida.",
    required: true,
    block: "Recepción",
    sector: "recepcion",
    responsibleRoles: ["asesor"],
    allowsNa: false,
    weight: 1,
    order: 3,
    priority: "medium",
    active: true,
  },
  {
    id: "or-04",
    text: "04. Identificación del propietario y conductor",
    description: "Datos completos del titular y conductor si corresponde.",
    required: true,
    block: "Recepción",
    sector: "recepcion",
    responsibleRoles: ["asesor"],
    allowsNa: false,
    weight: 1,
    order: 4,
    priority: "medium",
    active: true,
  },
  {
    id: "or-05",
    text: "05. Identificación del vehículo + KM",
    description: "VIN completo, modelo y kilometraje exacto tomado al recibir.",
    required: true,
    block: "Recepción",
    sector: "recepcion",
    responsibleRoles: ["asesor"],
    allowsNa: false,
    weight: 1,
    order: 5,
    priority: "high",
    active: true,
  },
  {
    id: "or-06",
    text: "06. Falla denunciada por el cliente",
    description: "La falla o requerimiento debe estar expresado de forma clara y completa.",
    required: true,
    block: "Recepción",
    sector: "recepcion",
    responsibleRoles: ["asesor", "tecnico"],
    allowsNa: false,
    weight: 1,
    order: 6,
    priority: "high",
    active: true,
  },
  {
    id: "or-07",
    text: "07. Observaciones de la unidad",
    description: "Inspección visual de la unidad registrada en pre orden y OR.",
    required: true,
    block: "Recepción",
    sector: "recepcion",
    responsibleRoles: ["asesor"],
    allowsNa: false,
    weight: 1,
    order: 7,
    priority: "medium",
    active: true,
  },
  {
    id: "or-08",
    text: "08. Comprobante de servicio DSP",
    description: "Creación e impresión del comprobante de servicio de ELSA.",
    required: true,
    block: "Recepción",
    sector: "recepcion",
    responsibleRoles: ["asesor"],
    allowsNa: true,
    weight: 1,
    order: 8,
    priority: "medium",
    active: true,
  },
  {
    id: "or-09",
    text: "09. Firma del cliente",
    description: "Firma, aclaración, DNI y fecha del cliente en recepción o retiro según corresponda.",
    required: true,
    block: "Recepción",
    sector: "recepcion",
    responsibleRoles: ["asesor"],
    allowsNa: false,
    weight: 1,
    order: 9,
    priority: "high",
    active: true,
  },
  {
    id: "or-10",
    text: "10. Carga del trabajo realizado en SIAC",
    description: "Detalle de la reparación realizada en sistema.",
    required: true,
    block: "Taller",
    sector: "taller",
    responsibleRoles: ["tecnico"],
    allowsNa: false,
    weight: 1,
    order: 10,
    priority: "high",
    active: true,
  },
  {
    id: "or-11",
    text: "11. Diagnóstico técnico",
    description: "Debe existir diagnóstico técnico claro con causa raíz.",
    required: true,
    block: "Taller",
    sector: "taller",
    responsibleRoles: ["tecnico"],
    allowsNa: false,
    weight: 1,
    order: 11,
    priority: "high",
    active: true,
  },
  {
    id: "or-12",
    text: "12. Registro de ampliaciones",
    description: "Registro de piezas detectadas, presupuestadas y motivo de reemplazo.",
    required: true,
    block: "Taller",
    sector: "repuestos",
    responsibleRoles: ["tecnico", "repuestos", "controller"],
    allowsNa: true,
    weight: 1,
    order: 12,
    priority: "high",
    active: true,
  },
  {
    id: "or-13",
    text: "13. Reparación realizada",
    description: "Descripción técnica detallada de la reparación efectuada.",
    required: true,
    block: "Taller",
    sector: "taller",
    responsibleRoles: ["tecnico"],
    allowsNa: false,
    weight: 1,
    order: 13,
    priority: "high",
    active: true,
  },
  {
    id: "or-14",
    text: "14. Tabla de mantenimiento técnica",
    description: "Checklist técnica completa con firma y fecha de técnico y controller.",
    required: true,
    block: "Taller",
    sector: "taller",
    responsibleRoles: ["tecnico", "controller"],
    allowsNa: true,
    weight: 1,
    order: 14,
    priority: "medium",
    active: true,
  },
  {
    id: "or-15",
    text: "15. Vale de repuestos",
    description: "Vale con firmas y fechas correspondientes.",
    required: true,
    block: "Repuestos",
    sector: "repuestos",
    responsibleRoles: ["tecnico", "repuestos"],
    allowsNa: true,
    weight: 1,
    order: 15,
    priority: "medium",
    active: true,
  },
  {
    id: "or-16",
    text: "16. Registro del tiempo aplicado",
    description: "Debe permitir individualizar cada ítem y parcializar tiempos.",
    required: true,
    block: "Taller",
    sector: "taller",
    responsibleRoles: ["tecnico"],
    allowsNa: false,
    weight: 1,
    order: 16,
    priority: "medium",
    active: true,
  },
  {
    id: "or-17",
    text: "17. Recorrido de prueba",
    description: "Validar sello de controller y kilómetros de inicio y fin.",
    required: true,
    block: "Control de calidad",
    sector: "control_calidad",
    responsibleRoles: ["controller"],
    allowsNa: true,
    weight: 1,
    order: 17,
    priority: "high",
    active: true,
  },
  {
    id: "or-18",
    text: "18. Firma de control de calidad",
    description: "Validación final de las reparaciones realizadas.",
    required: true,
    block: "Control de calidad",
    sector: "control_calidad",
    responsibleRoles: ["controller"],
    allowsNa: false,
    weight: 1,
    order: 18,
    priority: "high",
    active: true,
  },
  {
    id: "or-19",
    text: "19. Firma del técnico",
    description: "Firma o código de identificación del técnico sobre el checklist.",
    required: true,
    block: "Taller",
    sector: "taller",
    responsibleRoles: ["tecnico"],
    allowsNa: false,
    weight: 1,
    order: 19,
    priority: "medium",
    active: true,
  },
  {
    id: "or-20",
    text: "20. Firma de responsable de taller",
    description: "Debe estar relacionada con la fecha de cierre de la OR.",
    required: true,
    block: "Control de calidad",
    sector: "control_calidad",
    responsibleRoles: ["controller"],
    allowsNa: false,
    weight: 1,
    order: 20,
    priority: "medium",
    active: true,
  },
  {
    id: "or-21",
    text: "21. Registro de lavado",
    description: "Verificar reloj, firma y descripción del lavado.",
    required: true,
    block: "Lavado",
    sector: "lavado",
    responsibleRoles: ["lavador"],
    allowsNa: true,
    weight: 1,
    order: 21,
    priority: "medium",
    active: true,
  },
  {
    id: "or-22",
    text: "22. Checklist de lavado",
    description: "Debe existir checklist con tildes y control del proceso de lavado.",
    required: true,
    block: "Lavado",
    sector: "lavado",
    responsibleRoles: ["lavador"],
    allowsNa: true,
    weight: 1,
    order: 22,
    priority: "medium",
    active: true,
  },
];

export const PRE_DELIVERY_CHECKLIST_ITEMS: AuditTemplateItem[] = [
  {
    id: "pre-entrega-01",
    text: "01. Planilla de verificacion con firmas y sello de pre entrega.",
    description: "Auditar sobre legajo documental. Muestra objetivo: 3 legajos de planes y 3 de tradicional.",
    guidance: "Verificar que el legajo tenga la planilla completa, firmada y sellada.",
    required: true,
    block: "Legajo documental (3 planes + 3 tradicional)",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 1,
    active: true,
  },
  {
    id: "pre-entrega-02",
    text: "02. OR impresa con 48 hs. antes con el Vale a Taller de los materiales a utilizar. Evaluar tambien accesorios si corresponde.",
    description: "Debe estar emitida con anticipacion minima de 48 horas.",
    required: true,
    block: "Legajo documental (3 planes + 3 tradicional)",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 2,
    active: true,
  },
  {
    id: "pre-entrega-03",
    text: "03. Carga de combustible con fecha y hora, monto, km de la unidad, numero de ticket, sello y firma del responsable.",
    required: true,
    block: "Legajo documental (3 planes + 3 tradicional)",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 3,
    active: true,
  },
  {
    id: "pre-entrega-04",
    text: "04. Preparacion de la unidad con 48 hs. de anticipacion a la entrega, con fecha, firma y descripcion.",
    required: true,
    block: "Legajo documental (3 planes + 3 tradicional)",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 4,
    active: true,
  },
  {
    id: "pre-entrega-05",
    text: "05. Registro de lavado con fecha y firma del responsable con 24 hs. de anticipacion como minimo.",
    required: true,
    block: "Legajo documental (3 planes + 3 tradicional)",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 5,
    active: true,
  },
  {
    id: "pre-entrega-06",
    text: "06. Control final visual de calidad hasta el dia de la entrega.",
    required: true,
    block: "Legajo documental (3 planes + 3 tradicional)",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 6,
    active: true,
  },
  {
    id: "pre-entrega-07",
    text: "07. Cierre de preparacion de pre entrega con fecha, tilde en todos los campos correspondientes y firma.",
    required: true,
    block: "Legajo documental (3 planes + 3 tradicional)",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 7,
    active: true,
  },
  {
    id: "pre-entrega-08",
    text: "08. Check de Elsa con impresion mayor a 48 hs., completo, con firma y fecha de los responsables. Las fechas deben ser con 48 hs. de anticipacion a la entrega.",
    required: true,
    block: "Legajo documental (3 planes + 3 tradicional)",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 8,
    active: true,
  },
  {
    id: "pre-entrega-09",
    text: "09. Comprobante del servicio registrado en Elsa.",
    required: true,
    block: "Legajo documental (3 planes + 3 tradicional)",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 9,
    active: true,
  },
  {
    id: "pre-entrega-10",
    text: "10. Comprobante de verificacion de campaña.",
    required: true,
    block: "Legajo documental (3 planes + 3 tradicional)",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 10,
    active: true,
  },
  {
    id: "pre-entrega-11",
    text: "11. Hoja de ruta con fechas y nombre de la persona de contacto. Programacion con 48 hs. de anticipacion.",
    required: true,
    block: "Legajo documental (3 planes + 3 tradicional)",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 11,
    active: true,
  },
  {
    id: "pre-entrega-12",
    text: "12. Bitacora con registros de mantenimiento mensual. Check de Elsa de mantenimiento completo, con tilde en los campos que correspondan, fecha y firma.",
    required: true,
    block: "Legajo documental (3 planes + 3 tradicional)",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 12,
    active: true,
  },
  {
    id: "pre-entrega-13",
    text: "13. Codigo de Radio / SIAC controlado 48 hs. antes de la entrega. Si el portal no funciona, debe quedar aviso y reprogramacion.",
    required: true,
    block: "Legajo documental (3 planes + 3 tradicional)",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 13,
    active: true,
  },
  {
    id: "pre-entrega-14",
    text: "14. Orden y limpieza del sector de pre entrega.",
    required: true,
    block: "Control visual del sector de pre entrega",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 14,
    active: true,
  },
  {
    id: "pre-entrega-15",
    text: "15. Uso de protectores de unidades.",
    required: true,
    block: "Control visual del sector de pre entrega",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 15,
    active: true,
  },
  {
    id: "pre-entrega-16",
    text: "16. Unidades cerradas y con la llave de duplicado donde corresponde.",
    required: true,
    block: "Control visual del sector de pre entrega",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 16,
    active: true,
  },
  {
    id: "pre-entrega-17",
    text: "17. Orden y limpieza en deposito.",
    required: true,
    block: "Control visual del sector de pre entrega",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 17,
    active: true,
  },
  {
    id: "pre-entrega-18",
    text: "18. Bidones de aceite con tapa en el sector auditado.",
    required: true,
    block: "Control visual del sector de pre entrega",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 18,
    active: true,
  },
  {
    id: "pre-entrega-19",
    text: "19. Clasificacion correcta de residuos con tachos, bolsas y señalizacion adecuada.",
    required: true,
    block: "Control visual del sector de pre entrega",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 19,
    active: true,
  },
  {
    id: "pre-entrega-20",
    text: "20. Mesas y carros de trabajo ordenados y limpios.",
    description: "No debe haber basura, papeles, botellas, restos de comida ni elementos ajenos a la tarea.",
    required: true,
    block: "Control visual del sector de pre entrega",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 20,
    active: true,
  },
  {
    id: "pre-entrega-21",
    text: "21. Herramientas de trabajo en buen estado.",
    description: "No deben visualizarse herramientas dañadas, con arreglos precarios o incompletas.",
    required: true,
    block: "Control visual del sector de pre entrega",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 21,
    active: true,
  },
  {
    id: "pre-entrega-22",
    text: "22. Utilizacion de EPP.",
    required: true,
    block: "Control visual del sector de pre entrega",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 22,
    active: true,
  },
  {
    id: "pre-entrega-23",
    text: "23. Productos toxicos y/o inflamables rotulados.",
    required: true,
    block: "Control visual del sector de pre entrega",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 23,
    active: true,
  },
  {
    id: "pre-entrega-24",
    text: "24. Espacios de circulacion despejados.",
    required: true,
    block: "Control visual del sector de pre entrega",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 24,
    active: true,
  },
  {
    id: "pre-entrega-25",
    text: "25. Circulacion vehicular dentro del CE a 10 km/h con balizas encendidas.",
    required: true,
    block: "Control visual del sector de pre entrega",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 25,
    active: true,
  },
  {
    id: "pre-entrega-26",
    text: "26. Matafuegos en condiciones optimas.",
    description: "Controlar vencimiento, manometro en verde, acceso libre y correcta señalizacion.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 26,
    active: true,
  },
  {
    id: "pre-entrega-27",
    text: "27. Nichos hidrantes en condiciones optimas.",
    description: "Señalizado, de facil acceso, con mangueras ordenadas, conectadas y con lanza y llave o martillo. Auditable no medible.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "medium",
    allowsNa: true,
    weight: 1,
    order: 27,
    active: true,
  },
  {
    id: "pre-entrega-28",
    text: "28. Cableado en buen estado.",
    description: "No cables pelados ni encintados.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 28,
    active: true,
  },
  {
    id: "pre-entrega-29",
    text: "29. Productos toxicos y/o inflamables rotulados en el sector.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 29,
    active: true,
  },
  {
    id: "pre-entrega-30",
    text: "30. Bidones de aceite con tapa en el sector.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 30,
    active: true,
  },
  {
    id: "pre-entrega-31",
    text: "31. Clasificacion correcta de residuos.",
    description: "Se promediara con el resultado del tecnico PDI.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 31,
    active: true,
  },
  {
    id: "pre-entrega-32",
    text: "32. Mesas y carros de trabajo ordenados y limpios.",
    description: "Se promediara con el resultado del tecnico PDI.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 32,
    active: true,
  },
  {
    id: "pre-entrega-33",
    text: "33. Herramientas de trabajo en buen estado.",
    description: "Se promediara con el resultado del tecnico PDI.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 33,
    active: true,
  },
  {
    id: "pre-entrega-34",
    text: "34. Utilizacion de EPP y señalizacion de obligatoriedad.",
    description: "Todos los colaboradores deben contar con EPP acorde a su tarea y en perfecto estado. Se promediara con el resultado del tecnico PDI.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 34,
    active: true,
  },
  {
    id: "pre-entrega-35",
    text: "35. Espacios de circulacion despejados.",
    description: "Se promediara con el resultado del tecnico PDI.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 35,
    active: true,
  },
  {
    id: "pre-entrega-36",
    text: "36. Señalizacion de riesgos de puestos de trabajo y herramientas o maquinaria.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 36,
    active: true,
  },
  {
    id: "pre-entrega-37",
    text: "37. Botiquin de facil acceso con control de vencimientos e inventario.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "medium",
    allowsNa: false,
    weight: 1,
    order: 37,
    active: true,
  },
  {
    id: "pre-entrega-38",
    text: "38. Circulacion vehicular dentro del CE a 10 km/h con balizas encendidas.",
    description: "Se promediara con el resultado del tecnico PDI.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 38,
    active: true,
  },
  {
    id: "pre-entrega-39",
    text: "39. Descarte correcto de documentacion con datos personales y de contacto de clientes.",
    required: true,
    block: "Seguridad y ambiente / promedio con tecnico PDI",
    priority: "high",
    allowsNa: false,
    weight: 1,
    order: 39,
    active: true,
  },
];

export const STAFF: Record<Role, string[]> = {
  "Asesores de servicio": ["Mauro Gutierrez", "Cristian Cardozo", "Carlos Farina"],
  "Asesores de cita": ["Pablo Guantay"],
  "Técnicos": ["J. Araya", "N. Poclava", "R. Garcia", "P. Fernandez", "E. Cruz", "I. Alanoca"],
  "Subgerente de servicio": ["Subgerente 1"],
  "Jefe de Taller": ["Marcelo Pereyra"],
  "Garantía": ["Garantía 1"],
  "Repuestos": ["Repuestos 1"],
  "Jefe de Repuestos": ["Jefe Repuestos 1"],
  "Lavadero": ["Claudio Bravo", "Santiago Silva", "Alejandro Mamani"],
  "Pre Entrega": ["Baysse Fernando", "Paredes Gustavo", "Cañazares Otero", "Bedoya Victoria", "Luna Jimenez Alejandro", "Quispe Orlando David"],
  "Ordenes": ["Mauro Gutierrez", "Cristian Cardozo", "Carlos Farina"],
};

export const AUDIT_QUESTIONS: Record<Role, string[]> = {
  "Asesores de servicio": [
    "¿Se tiene la información necesaria para recibir al cliente? (Verificar historial en VW ElsaPro y SIAC)",
    "¿Se registran/verifican correctamente los datos del cliente? (Nombre, mail, dni, dirección, etc)",
    "¿Se registran/verifican correctamente los datos de la unidad? (VIN completo, modelo, km exacto)",
    "¿Se registran/verifican correctamente los datos del concesionario vendedor y fecha de venta?",
    "¿Se registran correctamente los requerimientos y observaciones en la OR?",
    "¿En caso de ruidos o fallas aleatorias, se involucra al personal de Taller/Controller?",
    "¿Se verifica la existencia de auxilio, extintor, gato, herramientas?",
    "¿Se verifica la presencia de objetos de valor del cliente y tuercas antirrobo?",
    "¿Se colocan fundas al volante y asiento delante del cliente?",
    "¿Se verifica funcionamiento del tablero, bocina, luces, nivel de combustible?",
    "¿Se controla visualmente el exterior del vehículo con el cliente?",
    "¿Se tomaron fotografías de la unidad al momento de la recepción?",
    "¿Se registra fecha/hora de ingreso e informa correctamente la fecha/hora prometida?",
    "¿Se ofrece servicio de Remis o traslado?",
    "¿Se explica al cliente el trabajo a realizar y se detalla presupuesto?",
    "¿Se consulta y registra la forma de pago? ¿Se informa el horario de atención?",
    "¿El cliente firmó la OR y se registró su nombre, DNI, parentesco y fecha?",
    "¿El asesor firmó y aclaró su nombre en la OR?",
    "¿Se cargaron correctamente los trabajos realizados en SIAC?",
    "¿Se registró fecha/hora de cierre en sistema y OR?",
    "¿Se adjunta toda la documentación correspondiente a la OR (pre orden, ElsaPro, etc)?",
    "¿El AS realizó seguimiento de los trabajos del Taller?",
    "¿El AS verificó el funcionamiento en presencia del cliente?",
    "¿Se solicitó autorización del cliente para ampliaciones y se registró en OR?",
    "¿Se explicó al cliente la factura detallando repuestos y mano de obra?",
    "¿Se informó al cliente sobre próximos servicios o mantenimientos?",
    "¿El cliente firmó la conformidad al retirar el vehículo?",
    "¿Se informa al cliente sobre la app Mi VW y sus beneficios?",
    "¿Se circula con el vehículo dentro del CE a 10km/h con balizas?",
    "¿Se gestionaron reclamos con solución, causa raíz y acciones (5 porqués)?",
    "¿Se respondió el reclamo dentro de las 48hs de su recepción?"
  ],
  "Asesores de cita": [
    "¿Se confirmó la cita con 24hs de antelación?",
    "¿Se verificó la disponibilidad de repuestos?",
    "¿Se registró correctamente el motivo de la visita?"
  ],
  "Técnicos": [
    "Se Registra de manera detallada el Diagnóstico (Lenguaje Técnico).",
    "Se Registra de manera detallada la Reparación realizada (Lenguaje Técnico).",
    "Se realiza el respectivo Control de Calidad con los recorridos correspondientes (Verificar KM).",
    "Firma en cada campo de diagnóstico y reparación realizada. Firma de Jefe de Taller.",
    "Utiliza los Protectores en la unidad (exterior e interior cuando se desacomodan).",
    "Informa al Jefe de Taller las ampliaciones de trabajo necesarias y solicita presupuesto.",
    "Se llevan a cabo todas las tareas descriptas en el Check List de Mantenimiento.",
    "Registro del tiempo aplicado, impreso por reloj costómetro + firma del técnico.",
    "Piezas sustituidas en bolsas colocadas en Estante.",
    "Bidones de aceite con tapa.",
    "Registro de devolución e ingresos de HHEE.",
    "Herramientas de trabajo en buen estado (sin arreglos precarios).",
    "Utilización de EPP acorde a su tarea y en perfecto estado.",
    "Productos tóxicos y/o inflamables rotulados.",
    "Espacios de circulación despejados.",
    "Descarte correcto de documentación con datos personales de clientes.",
    "Circulación vehicular dentro del CE a 10km/h con balizas encendidas."
  ],
  "Subgerente de servicio": [
    "¿Se supervisó el cumplimiento de los procesos de recepción y entrega?",
    "¿Se verificó la correcta carga de datos en SIAC y ElsaPro?",
    "¿Se atendieron reclamos de clientes en tiempo y forma (48hs)?",
    "¿Se controló la calidad de las reparaciones y el orden del taller?",
    "¿Se verificó la firma de conformidad de los clientes en las OR?"
  ],
  "Jefe de Taller": [
    "Verifica la utilización de los protectores para vehículos en taller.",
    "Control del orden y limpieza del taller (mesas, carros, residuos).",
    "Control del orden y limpieza del lavadero.",
    "Control del orden y limpieza sala de aceite (área ventilada).",
    "Firma OR al finalizar los trabajos.",
    "Se controla que se completen correctamente los Check List de Mantenimiento.",
    "Se realiza inventario de HH de técnicos (cada 6 meses).",
    "Controla la colocación de residuos de servicios en baúl/caja del vehículo.",
    "Se controla el adecuado uso y seguridad de los vehículos de los clientes en taller.",
    "Seguimiento y actualización de planilla de uso de HHEE.",
    "Control Físico de HHEE.",
    "Cumplimiento de calibración de HHEE.",
    "Se realiza inventario de HHEE y HHCC (Kit experto).",
    "Cumplimiento de calendario de control de equipos (mantenimiento preventivo).",
    "Se formula planes de acción y se realiza seguimiento de programa de VW (Q Checks).",
    "Gestiona la respuesta inmediata a los reclamos de clientes (48h).",
    "Se realizan devoluciones a los colaboradores (Resultados y mejoras).",
    "Matafuegos en condiciones óptimas (vencimiento, presión).",
    "Nichos hidrantes en condiciones óptimas (señalizado, mangueras, lanza).",
    "Cableado en buen estado (sin cables pelados ni zapatillas).",
    "Productos tóxicos y/o inflamables rotulados.",
    "Bidones de aceite con tapa.",
    "Herramientas de trabajo en buen estado.",
    "Utilización de EPP y señalización de obligatoriedad.",
    "Elevadores con mantenimiento al día (etiqueta de control).",
    "Espacios de circulación despejados.",
    "Señalización de riesgos de puestos de trabajo y maquinaria.",
    "Botiquín de fácil acceso y con fechas vigentes."
  ],
  "Garantía": [
    "Avance de Campañas (Recall, Taller, Pre-entrega).",
    "Comunicación de Campañas (Evidencia de contacto semanal).",
    "OR Garantías (Identificación, VIN, KM, Falla, Firmas).",
    "Seguimiento de clientes a la espera de repuestos en Gtía.",
    "Realiza plan de acción de los desvíos detectados en la última auditoría.",
    "5S - Espacio de trabajo ordenado y limpio.",
    "Gestión de Reclamos con análisis de los 5 por qué.",
    "Control de acceso y uso de ElsaPro para todo el equipo.",
    "Control del resguardo de piezas para cuando la marca lo solicite.",
    "Reclamo de garantía: control de carga de todas las campañas en Elsa.",
    "Campañas de pre entrega: contacto con el cliente por demora."
  ],
  "Repuestos": [
    "Control físico OK (Ubicación aleatoria 10 ítems).",
    "Control físico OK (Cantidad aleatoria 10 ítems).",
    "Implementación Proceso de Prepicking OK (24h/48h/72h).",
    "Ingreso de stock en el día de llegada al concesionario.",
    "Procesos de Disposición de Materiales Vencidos (Etiquetado por año).",
    "Orden y Limpieza del sector.",
    "FIFO (First In First out) - FEFO.",
    "Identificación de piezas.",
    "Separación física (metal con metal, film o cartón).",
    "Contenedores para recipientes con líquidos (bateas).",
    "Identificación de locación para cada artículo en stock.",
    "Clasificación correcta de residuos.",
    "Almacenaje de repuestos (distancia al techo, estiba segura).",
    "Espacios de circulación despejados."
  ],
  "Jefe de Repuestos": [
    "Limpieza de todo el sector (incluye carga y descarga).",
    "Control físico OK (Ubicación).",
    "Control físico OK (Cantidad).",
    "Implementación Proceso de Prepicking OK.",
    "Procesos de Disposición de Materiales Vencidos.",
    "Identificación de locación para cada artículo en stock.",
    "Seguimiento de grado de servicio.",
    "Se formula planes de acción y se realiza seguimiento de programas de VW.",
    "Respuesta de reclamos dentro de las 48 hs.",
    "Se realizan devoluciones a los colaboradores.",
    "Matafuegos en condiciones óptimas.",
    "Nichos hidrantes en condiciones óptimas.",
    "Cableado en buen estado.",
    "Productos tóxicos y/o inflamables rotulados.",
    "Clasificación correcta de residuos.",
    "Almacenaje de repuestos (distancia al techo, estiba).",
    "Espacios de circulación despejados.",
    "Señalización de riesgos de puestos de trabajo.",
    "Botiquín de fácil acceso."
  ],
  "Lavadero": [
    "Firma correspondiente en Orden de Reparación.",
    "Control del orden y limpieza del lavadero (sin basura en piso).",
    "Clasificación correcta de residuos.",
    "Adecuado uso y seguridad de los vehículos de los clientes (10km/h, balizas).",
    "Productos tóxicos y/o inflamables rotulados.",
    "Utilización de EPP acorde a su tarea.",
    "Espacios de circulación despejados.",
    "Lavado 0 Km / Limpieza habitáculo (seco y sin marcas)."
  ],
  "Pre Entrega": [
    ...PRE_DELIVERY_CHECKLIST_ITEMS.map((item) => item.text)
  ],
  "Ordenes": [
    "1. Número de OR: Colocar el Número de Seis Dígitos.",
    "2. Ingreso / Entrega de unidad (datos completos): Hora de ingreso, Fecha y hora prevista de entrega. Fecha de cierre.",
    "3. Inspección inicial (recepción): Verifica existencia de auxilio, extintor, gato, herramientas, objetos de valor.",
    "4. Presupuesto ofrecido: De acuerdo a última circular de Precios Oficiales + forma de pago.",
    "5. Identificación del Propietario y/o chofer: Datos completos (Nombre, Apellido, Teléfono, Dirección, Correo electrónico, etc.)-Indicar en conductor si corresponde a titular o no.",
    "6. Identificación del Vehículo + KM: Datos completos (VIN completo, modelo) + km exacto que evidencia en recepción.",
    "7. Concesionario Vendedor y Fecha de entrega: CE que realizó la entrega del vehículo + fecha de comienzo de periodo de garantía.",
    "8. Falla denunciada por el Cliente / Requerimiento: Comentario expresado por el Cliente. El AS deberá asegurar que la información clara y completa.",
    "9. Registro de observaciones en unidad (Inspección inicial): Realizar la revisión del vehículo junto al Cliente en el momento de recepción, Reflejar en pre orden y OR todos los detalles de la unidad.",
    "10. Creación del Comprobante de servicio DSP: Creación e impresión del comprobante de servicio de ELSA.",
    "11. Enumera los Trabajos por N° de Ítem: Identificación de cada trabajo encargado a fin de poder individualizar su diagnóstico, reparación y tiempo aplicado.",
    "12. Firma del Cliente en conformidad con las fallas a verificarse: Se recomienda Firma, aclaración, DNI, fecha.",
    "13. Firma del Cliente al retirar el vehículo: Firma, aclaración, DNI - fecha de retiro (de mano del cliente).",
    "14. Validación de Ampliaciones de OR: Firma del Cliente aceptando los trabajos realizados en la ampliación. Campos de ampliación de trabajo completos.",
    "15. Carga de trabajo realizado en SIAC: Detalle de la reparación realizada.",
    "16. Diagnóstico de Taller: Descripción técnica del diagnóstico efectuado y causa raíz de la avería.",
    "17. Campo de Ampliaciones (Registro): Registro de piezas detectadas, presupuestadas, motivo de reemplazo, fecha y hora.",
    "18. Reparación realizada: Descripción técnica detallando la Reparación efectuada por el operario.",
    "19. Tabla de mantenimiento (AS): Completa con registro de patente, fecha y firma de AS.",
    "20. Tabla de mantenimiento (Técnico + Controller): Correctamente tildada, con firma y fechas correspondientes.",
    "21. Vale de Repuestos: Con firma y fechas correspondientes (técnico + repuestos).",
    "22. Registro del tiempo aplicado (Reloj costómetro): Que permita la individualización de cada ítem. Realizar la parcialización y totalización de los tiempos.",
    "23. Recorrido de prueba de controllers: Verificar sello del CC, km tanto de inicio como de finalizado del recorrido.",
    "24. Firma de Control de Calidad: Validando el OK de las Reparaciones realizadas.",
    "25. Firma del técnico (en el checklist): Mediante código de identificación o firma.",
    "26. Firma de Resp. de taller + Fecha: Estará relacionada a la Fecha de cierre de la Orden de Reparación.",
    "27. Lavador (Reloj + Firma + Descripción): Verificar: Reloj + Firma + Descripción.",
    "28. Lavador (Checklist): Coloca tildes en check list (lavado)."
  ],
};